version: '3'
services:
  postgres:
    container_name: docker-postgresql
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=localhost
      - POSTGRES_PASSWORD=localhost
      - POSTGRES_DB=localhost
